### ISSUE TITLE
A lot of blank lines when running build (RDT-359)

### ISSUE THREAD

**Issue by enricobertolotti** [espressif/esp-idf-ci-action#28] opened 2023-01-09 20:25 UTC
Is there a reason there are so many blank lines when running this action? All in all this action outputs around ~1k lines, most of them blank. It makes it hard to inspect the output

<img width="639" alt="image" src="https://user-images.githubusercontent.com/73933383/211400770-e6847430-18c5-4b82-a9d7-91100ed6ec63.png">

### Setup:
Self-hosted on ubuntu (rpi)

### Workflow:
```yaml
jobs:
  build:
    steps:
      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.0
          target: esp32s2
          path: '.'
```

**Comment by kumekay** [comment] 2023-01-09 20:36
Hello @enricobertolotti
It looks like the build output is not visible at all. Are you able to read the logs of ninja?

**Comment by kumekay** [comment] 2023-01-09 20:56
@enricobertolotti

I was able to reproduce the issue, probably the root cause of this is error hints system added in ESP-IDF 5.0,

The problem present with IDF 5.0 https://github.com/kumekay/ci_playground/actions/runs/3877593140/jobs/6612783850

But it works fine with IDF 4.4
https://github.com/kumekay/ci_playground/actions/runs/3877611222/jobs/6612821848

**Comment by tajnymag** [comment] 2023-10-24 16:29
Can confirm. Still happening on the current version of the action and IDF 5.0.2

**Comment by fhrbata** [comment] 2024-01-15 08:55
Hello,

I tried it and it seems this is presented in v5.0 only. `fail` - empty lines instead of cmakes progress output.

- v4.4 - ok
- v5.0 - fail
- v5.1 - ok
- v5.2-beta2 - ok
- latest - ok

I will take a look what is missing in v5.0. Thank you

**Comment by fhrbata** [comment] 2024-01-15 11:24
Hello,

this should be already fixed by https://github.com/espressif/esp-idf/commit/8be7a054871cd041a242a9aa8f7e83e9a7a28ee1. The problem seems to be that `v5.0` docker image does not contain this fix, because it was last updated Dec 2, 2022. I guess the major release image is not updated once released. I tried `v5.0.5` and it seems to be working as expected. You can also try to use `release-v5.0` with latest `v5.0` fixes.

@kumekay  I believe this can be closed.

Thank you

**Comment by kumekay** [comment] 2024-01-18 14:02
@fhrbata Thank you for taking a look

**Closed as completed by kumekay** 2024-01-18 14:02 UTC
